version: '3.7'

services:

  workspace:
    build:
      context: ./workspace
    ports:
    - 8000:8000
    volumes:
      - ../app:/var/www/app:cached
    working_dir: /var/www/app

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ../app/public:/var/www/app/public:cached
      - ../app/storage:/var/www/app/storage:cached

  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - 9000:9000
    volumes:
      - ../app:/var/www/app:cached

  mysql:
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db1

volumes:
  db-data: